### ISSUE TITLE
Create API endpoints to access data from takes and teaches tables

### ISSUE THREAD

**Issue by knightofcookies** [knightofcookies/academic-tracking#4]
### Tasks

- [x] Instructor-wise list of courses offered in various sessions
- [x] Course-wise list of sessions the course was offered in
- [x] List of students (with grades) who took a course in a session
- [x] Student-wise list of courses taken in various sessions and semesters
